### ISSUE TITLE
"Max. recursion depth with nested structures exceeded" error

### ISSUE THREAD

**Issue by JesseCrocker** [darold/pgbadger#544]
I just updated from 9.2 to 11.1, and a log file that parsed properly with 9.2 now produces this error:
```
$ pgbadger db.log

Max. recursion depth with nested structures exceeded at /usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/Storable.pm line 328, at /usr/local/bin/pgbadger line 14021.

can not load incompatible binary data, binary file is from version < 4.0.
LOG: Ok, generating html report...
```

out.html is produced, but it shows no queries. It seems like the log is parsed properly, and that error happens while generating the report.

Im using MacOS and installing with homebrew, but i also tried downloading directly from github and have the same issue.

**Comment by darold** [comment]
Hi Jesse,

pgBadger v11.x is not compatible with binary files generated in incremental mode by old pgbadger version this is why you have the message `can not load incompatible binary data, binary file is from version < 4.0`. However this should not prevent pgbadger to generate new reports.

Please download an use latest development code and report the new error messages, the issue could have been fixed.

**Comment by JesseCrocker** [comment]
The `can not load incompatible binary data, binary file is from version < 4.0.` message seems misplaced, i dont use incremental mode at all, the only file in my CWD is the database log file, and i dont think i ever used pgbadger < 4.0.

I checked out master@0dbe0905e98e9ed67f6e57f2947b6e59bc8f8277, and still getting the same error
```
Max. recursion depth with nested structures exceeded at /usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/Storable.pm line 328, at /Users/jesse/Downloads/pgbadger-master/pgbadger line 14077.

can not load incompatible binary data, binary file is from version < 4.0.
LOG: Ok, generating html report...
```

**Comment by darold** [comment]
I think the problem is related to your operating system, I don't have a MacOs at my hand to try to fix it.
